name: Auto update go dependencies

on:
  schedule:
    # runs daily at 12:00 am
    - cron: '25 0 * * *'
  workflow_dispatch:

jobs:
  auto-update-go-dependencies:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    # - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1      
             
    - name: Run auto dependency update 
      uses: romoh/dependencies-autoupdate@main
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        update-command: "dart pub upgrade --major-versions"